package com.cdutcm.tcms.biz.service;

import com.cdutcm.tcms.biz.model.ExecRecipel;

public interface ExecRecipelService {
	 /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exec_recipel
     *
     * @mbggenerated Fri Mar 02 15:05:17 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exec_recipel
     *
     * @mbggenerated Fri Mar 02 15:05:17 CST 2018
     */
    int insert(ExecRecipel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exec_recipel
     *
     * @mbggenerated Fri Mar 02 15:05:17 CST 2018
     */
    int insertSelective(ExecRecipel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exec_recipel
     *
     * @mbggenerated Fri Mar 02 15:05:17 CST 2018
     */
    ExecRecipel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exec_recipel
     *
     * @mbggenerated Fri Mar 02 15:05:17 CST 2018
     */
    int updateByPrimaryKeySelective(ExecRecipel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table exec_recipel
     *
     * @mbggenerated Fri Mar 02 15:05:17 CST 2018
     */
    int updateByPrimaryKey(ExecRecipel record);
    


}
